{{- if .Values.obo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}-obo
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.obo.stateKey }}
  state-key: {{ . | quote }}
  {{- end }}
  {{- with .Values.obo.storeKey }}
  store-key: {{ . | quote }}
  {{- end }}
{{- end }}
