// Code generated by controller-gen. DO NOT EDIT.
// Hand-rolled equivalent for builds without controller-gen.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyObject implements runtime.Object.
func (in *ChannelRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this ChannelRoute.
func (in *ChannelRoute) DeepCopy() *ChannelRoute {
	if in == nil {
		return nil
	}
	out := new(ChannelRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of this ChannelRoute into out.
func (in *ChannelRoute) DeepCopyInto(out *ChannelRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyInto copies all fields of this ChannelRouteSpec into out.
func (in *ChannelRouteSpec) DeepCopyInto(out *ChannelRouteSpec) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy returns a deep copy of this ChannelRouteSpec.
func (in *ChannelRouteSpec) DeepCopy() *ChannelRouteSpec {
	if in == nil {
		return nil
	}
	out := new(ChannelRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of this ChannelRouteStatus into out.
func (in *ChannelRouteStatus) DeepCopyInto(out *ChannelRouteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this ChannelRouteStatus.
func (in *ChannelRouteStatus) DeepCopy() *ChannelRouteStatus {
	if in == nil {
		return nil
	}
	out := new(ChannelRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ChannelRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this ChannelRouteList.
func (in *ChannelRouteList) DeepCopy() *ChannelRouteList {
	if in == nil {
		return nil
	}
	out := new(ChannelRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields of this ChannelRouteList into out.
func (in *ChannelRouteList) DeepCopyInto(out *ChannelRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChannelRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
